name: "main"
on:
  - push

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
      datetime: ${{ steps.get-datetime.outputs.datetime }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"
      - id: get-datetime
        run: echo "::set-output name=datetime::$(date +'%Y%m%d%H%M%S')"

  build:
    needs: [ configure ]
    container:
      image: zondax/rust-ci:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: yarn install
      - name: Run test
        run: yarn test
